In [1]:
import cv2
import numpy as np
from datetime import datetime


video = cv2.VideoCapture(0)#giving the access of the camera 

background=0
for i in range(30):
    check,background = video.read()

while True:
    check,image=video.read()
    print(check)
    print(image)
    
    if not check:
        break
    if check:
        hsv =cv2.cvtColor(image,cv2.COLOR_BGR2HSV)

        #cv2.imshow('hsv',hsv)
        #To find the lower and upper values of red colour in hsv , you need to print the red values of bgr  
        #convert it to hsv
        #To apply the other colours need to find the maximum and minimum values of that particular colour in bgr and then convert it to hsv
        
        
        
        l_red=np.array([0,100,100])#lower value of red in hsv
        u_red=np.array([10,255,255])#upper value of red in hsv
        
        mask1=cv2.inRange(hsv,l_red,u_red)
        cv2.imshow('mask1',mask1)
        
        
        #Remove the noise
        mask1=cv2.morphologyEx(mask1,cv2.MORPH_OPEN,np.ones((3,3),np.uint8), iterations=2)
        mask1=cv2.morphologyEx(mask1,cv2.MORPH_CLOSE,np.ones((3,3),np.uint8), iterations=1) 
        
        
        part1=cv2.bitwise_and(background,background,mask=mask1)#detects the background containing red colour only
        cv2.imshow('part1',part1)
        
        
        mask2=cv2.bitwise_not(mask1)
        
        part2=cv2.bitwise_and(image,image,mask=mask2)#detects the  background containing every colour except red
        #cv2.imshow("part2",part2)
        
        
        cv2.imshow("invisible cloak", part1+part2)
        
        
 #NOTE: When you runs the programme just stay away from the video source just to make sure that webcam can capture the background
        #otherwise the code will not be said as magical cloak as it won't be able to capture the background.
        
        
    
    if cv2.waitKey(5) == ord('q'):
        break  

        
video.release()
cv2.destroyAllWindows()

True
[[[  2   4   0]
  [  1   3   0]
  [  1   3   0]
  ...
  [ 69  56  25]
  [ 75  55  23]
  [ 75  55  23]]

 [[  0   4   0]
  [  0   4   0]
  [  0   6   0]
  ...
  [ 72  57  26]
  [ 68  57  26]
  [ 67  56  25]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 78  53  26]
  [ 78  56  20]
  [ 78  56  20]]

 ...

 [[  0  13   2]
  [  0  14   3]
  [  4  13   5]
  ...
  [ 91 102  76]
  [ 98 103  70]
  [ 95 100  68]]

 [[  3  13   0]
  [  3  13   0]
  [  3  12   4]
  ...
  [ 77  88  71]
  [ 75  87  65]
  [ 75  87  65]]

 [[  6  13  13]
  [  5  12  12]
  [  4  11  10]
  ...
  [ 78  86  88]
  [ 69  85  86]
  [ 69  85  86]]]


AttributeError: module 'numpy' has no attribute 'unit8'